import {Player} from "./player.js"; import {Particles} from "./particles.js"; import {Projectile} from "./combat.js"; import {LEVELS,drawBackground} from "./levels.js"; import {createBoss} from "./bosses.js"; import {Save} from "./save.js"; import {EQUIPMENT,CLOTHES} from "./economy.js"; import {createTrack,stream} from "./music.js"; import {shopHTML} from "./shop.js"; import {inventoryHTML} from "./inventory.js"; import {apartmentHTML} from "./apartment.js"; import {streamHTML} from "./streaming.js"; import {DISCS} from "./discs.js"; import {DIALOGUES} from "./dialogue.js"; import {toast} from "./ui.js";
const $=id=>document.getElementById(id);
export class Game {
 constructor(canvas,state){this.canvas=canvas;this.ctx=canvas.getContext("2d");this.s=state;this.keys={};this.projectiles=[];this.particles=new Particles();this.camera=0;this.level=LEVELS.city;this.player=new Player(150,600);this.player.hp=state.health;this.player.maxHp=state.maxHealth;this.player.music=state.musicEnergy;this.paused=false;this.boss=null;this.dialog=null;this.running=false;this.last=performance.now();this.onKeyDown=e=>{this.keys[e.key.toLowerCase()]=true;if(e.key.toLowerCase()==="escape")this.pause()};this.onKeyUp=e=>this.keys[e.key.toLowerCase()]=false;this.onCanvasClick=e=>this.canvasClick(e);this.onResize=()=>this.resize();window.addEventListener("keydown",this.onKeyDown);window.addEventListener("keyup",this.onKeyUp);window.addEventListener("resize",this.onResize);canvas.addEventListener("click",this.onCanvasClick);this.resize()}
 destroy(){this.running=false;cancelAnimationFrame(this.frame);window.removeEventListener("keydown",this.onKeyDown);window.removeEventListener("keyup",this.onKeyUp);window.removeEventListener("resize",this.onResize);this.canvas.removeEventListener("click",this.onCanvasClick)}
 resize(){const d=devicePixelRatio||1;this.canvas.width=innerWidth*d;this.canvas.height=innerHeight*d;this.ctx.setTransform(d,0,0,d,0,0);this.W=innerWidth;this.H=innerHeight}
 start(){if(this.running)return;this.running=true;this.last=performance.now();this.frame=requestAnimationFrame(t=>this.loop(t));if(!this.s.story.prologue){this.s.story.prologue=true;this.startDialogue(DIALOGUES.prologue,()=>{this.toast("Выйди в город и найди друга");this.autosave()})}}
 loop(t){if(!this.running)return;const dt=Math.min(.033,(t-this.last)/1000);this.last=t;if(!this.paused)this.update(dt);this.draw();this.frame=requestAnimationFrame(x=>this.loop(x))}
 update(dt){this.player.update(dt,this.keys,this.level);this.camera=Math.max(0,Math.min(this.level.width-this.W,this.player.x-this.W*.4));this.projectiles.forEach(p=>p.update(dt));this.projectiles=this.projectiles.filter(p=>p.life>0&&p.x>-100&&p.x<this.level.width+100);if(this.boss){this.boss.update(dt,this);for(const p of this.projectiles){if(p.type==="music"&&p.x>this.boss.x&&p.x<this.boss.x+this.boss.w&&p.y>this.boss.y&&p.y<this.boss.y+this.boss.y+this.boss.h){p.life=0;this.boss.takeDamage(p.damage,this)}}for(const p of this.projectiles){if(p.type==="danger"&&this.player.x+this.player.w>p.x-p.r&&this.player.x<p.x+p.r&&this.player.y+this.player.h>p.y-p.r&&this.player.y<p.y+p.r&&this.player.inv<=0){this.damage(1);p.life=0}}}this.particles.update(dt);this.player.music=Math.min(100,this.player.music+10*dt);this.updateHint();this.syncHUD()}
 draw(){const c=this.ctx;c.clearRect(0,0,this.W,this.H);drawBackground(c,this.level,this.W,this.H,this.camera);c.save();c.translate(-this.camera,0);for(const p of this.level.platforms){c.fillStyle=this.level.bg==="city"?"#252d47":"#343434";c.fillRect(p.x,p.y,p.w,p.h);c.fillStyle="#111827";c.fillRect(p.x,p.y,p.w,5)}for(const o of this.level.objects){c.font="30px sans-serif";c.fillText(({computer:"💻",shop:"🏪",friend:"🧑‍🎤",basement:"⬇️",alley:"💿",bench:"🪑",studio:"🎙️"})[o.type]||"•",o.x,o.y)}this.projectiles.forEach(p=>p.draw(c));this.player.draw(c);if(this.boss)this.boss.draw(c);this.particles.draw(c);c.restore()}
 syncHUD(){$("moneyHud").textContent="₽ "+this.s.money.toLocaleString("ru-RU");$("chapterHud").textContent="ГЛАВА "+this.s.currentChapter;$("musicFill").style.width=this.player.music+"%";$("hearts").innerHTML=Array.from({length:this.player.maxHp},(_,i)=>`<span class="heart ${i>=this.player.hp?"empty-heart":""}">${i<this.player.hp?"❤️":"🖤"}</span>`).join("");$("bossHud").classList.toggle("hidden",!this.boss);if(this.boss){$("bossFill").style.width=this.boss.hp/this.boss.maxHp*100+"%";$("bossName").textContent="BOSS — "+this.boss.name;$("bossPhase").textContent="PHASE "+this.boss.phase}}
 nearObject(){return this.level.objects.find(o=>Math.abs(o.x-this.player.x)<90&&Math.abs(o.y-this.player.y)<130)}
 updateHint(){const o=this.nearObject();$("interactionHint").textContent=o?"E — "+({computer:"создать бит (+25 ₽)",shop:"зайти в магазин",friend:"поговорить",basement:"спуститься в подвал",alley:"обыскать переулок",bench:"передохнуть",studio:"записать трек"}[o.type]||"взаимодействовать"):""}
 canvasClick(e){const r=this.canvas.getBoundingClientRect(),x=e.clientX-r.left+this.camera,y=e.clientY-r.top;if(this.level.objects.some(o=>o.type==="computer"&&Math.abs(o.x-x)<70&&Math.abs(o.y-y)<90))this.clickComputer()}
 interact(){const o=this.nearObject();if(!o)return;return ({computer:()=>this.clickComputer(),shop:()=>this.openShop(),alley:()=>this.findDisc(),bench:()=>this.toast("Иногда пауза тоже часть трека."),friend:()=>this.meetFriend(),basement:()=>this.enterBasement(),studio:()=>this.publish()})[o.type]?.()}
 startDialogue(lines,onEnd){this.dialog={lines,index:0,onEnd};this.paused=true;this.renderDialogue()}
 renderDialogue(){const [speaker,line]=this.dialog.lines[this.dialog.index];$("panelContent").innerHTML=`<div class="small-label">${speaker}</div><h1>${speaker}</h1><p>${line.replace("{name}",this.s.playerName)}</p><button data-dialog-next>${this.dialog.index===this.dialog.lines.length-1?"ПРОДОЛЖИТЬ":"ДАЛЕЕ"}</button>`;$("panelScreen").classList.remove("hidden")}
 nextDialogue(){if(!this.dialog)return;if(++this.dialog.index<this.dialog.lines.length)return this.renderDialogue();const done=this.dialog.onEnd;this.dialog=null;$("panelScreen").classList.add("hidden");this.paused=false;done?.()}
 meetFriend(){if(this.s.story.friendMet)return this.enterBasement();this.startDialogue(DIALOGUES.friend,()=>{this.s.story.friendMet=true;this.s.story.basement=true;if(!this.s.unlockedLocations.includes("basement"))this.s.unlockedLocations.push("basement");this.enterBasement();this.autosave()})}
 enterBasement(){this.level=LEVELS.basement;this.player.x=120;this.player.y=600;this.camera=0;this.toast("ПОДВАЛ — твоя первая студия")}
 clickComputer(){this.s.money+=25;toast("+25 ₽");this.particles.burst(this.player.x+20,this.player.y,"#ffd166",8,3);this.autosave()}
 attack(music=false){if(this.player.attackCd>0)return;if(music){if(this.player.music<20)return this.toast("Недостаточно MUSIC");this.player.music-=20;this.projectiles.push(new Projectile(this.player.x+(this.player.facing>0?45:-10),this.player.y+30,this.player.facing*12,0,55,"music",11));this.player.attackCd=.22;this.particles.burst(this.player.x+this.player.facing*35,this.player.y+30,"#5de1ff",7,4)}else{this.player.attackCd=.3;for(const p of this.projectiles)if(p.type==="danger"&&Math.abs(p.x-this.player.x)<90)p.life=0}}
 special(){if(this.player.music<45)return this.toast("Нужно 45 MUSIC");this.player.music-=45;this.projectiles.push(new Projectile(this.player.x,this.player.y,this.player.facing*15,-1,80,"music",24));this.toast("BEAT DROP!")}
 damage(n){if(this.player.inv>0)return;this.player.hp-=n;this.player.inv=.9;this.player.vx=-this.player.facing*6;this.particles.burst(this.player.x,this.player.y+30,"#ff496d",14,5);if(this.player.hp<=0)this.lose()}
 warning(r){this.particles.burst(r.x+r.w/2,r.y,"#ff496d",20,2)}
 lose(){this.paused=true;this.s.health=3;this.s.musicEnergy=100;this.player.hp=3;this.player.music=100;$("panelContent").innerHTML=`<h1>ВЫ ПРОИГРАЛИ</h1><p>Кажется, школа всё-таки ждёт вас...</p><button data-retry-boss>ПОПРОБОВАТЬ ЕЩЁ РАЗ</button>`;$("panelScreen").classList.remove("hidden")}
 bossDefeated(b){if(!this.s.bossesDefeated.includes("mom"))this.s.bossesDefeated.push("mom");this.boss=null;this.paused=true;this.s.health=3;$("panelContent").innerHTML=`<h1>BOSS DEFEATED</h1><p>${b.name} повержен. Путь продолжается.</p><button data-close-panel>ПРОДОЛЖИТЬ</button>`;$("panelScreen").classList.remove("hidden");this.autosave()}
 startMom(){this.level=LEVELS.boss;this.player.x=200;this.player.y=600;this.boss=createBoss("mom");this.toast("BOSS — МАМА")}
 openShop(){this.paused=true;$("panelContent").innerHTML=shopHTML(this.s);$("panelScreen").classList.remove("hidden")}; openInventory(){this.paused=true;$("panelContent").innerHTML=inventoryHTML(this.s);$("panelScreen").classList.remove("hidden")}; openApartment(){this.paused=true;$("panelContent").innerHTML=apartmentHTML(this.s);$("panelScreen").classList.remove("hidden")}; openStream(){this.paused=true;$("panelContent").innerHTML=streamHTML(this.s);$("panelScreen").classList.remove("hidden")}
 publish(){const r=createTrack(this.s,"My First Track");this.toast(`ТРЕК ГОТОВ • ${r.quality}/100 • +${r.income} ₽`);this.autosave();if(this.s.equipment.mic!=="old"&&!this.s.bossesDefeated.includes("mom"))this.startDialogue(DIALOGUES.momBoss,()=>this.startMom())}
 doStream(){const r=stream(this.s);if(!r)return this.toast("Нужны камера и компьютер");this.toast(`LIVE • ${r.viewers} зрителей • +${r.income} ₽`);this.autosave();$("panelScreen").classList.add("hidden");this.paused=false}
 buyEquip(type,id){const item=EQUIPMENT[type]?.[id];if(!item||this.s.money<item.price)return this.toast("Недостаточно денег");this.s.money-=item.price;this.s.equipment[type]=id;this.toast("КУПЛЕНО");this.autosave();this.openShop()}; buyCloth(id){const c=CLOTHES.find(x=>x[0]===id);if(!c||this.s.clothes.includes(id)||this.s.money<c[2])return;this.s.money-=c[2];this.s.clothes.push(id);this.s.equippedClothes.push(id);this.autosave();this.openShop()}; buyFurniture(id){const prices={bed:5000,sofa:8000,tv:12000,desk:3000,speakers:15000,panels:22000,rgb:10000,chair:7000},price=prices[id];if(!price||this.s.furniture.includes(id)||this.s.money<price)return;this.s.money-=price;this.s.furniture.push(id);this.autosave();this.openApartment()}
 findDisc(){const pool=DISCS.filter(d=>!this.s.discs.some(x=>x.id===d.id));if(!pool.length)return this.toast("Переулок уже пуст.");const d=pool[Math.floor(Math.random()*pool.length)];this.s.discs.push(d);this.toast("💿 НАЙДЕН ДИСК: "+d.name);this.autosave()}; autosave(){this.s.health=this.player.hp;this.s.musicEnergy=this.player.music;Save.save(this.s)}; toast(t){toast(t)}; pause(){if(!$("panelScreen").classList.contains("hidden"))return;this.paused=!this.paused;$("pauseScreen").classList.toggle("hidden",!this.paused)}
}
