import {Player} from './player.js';import {Particles} from './particles.js';import {Projectile} from './combat.js';import {LEVELS,drawBackground} from './levels.js';import {createBoss} from './bosses.js';import {Save} from './save.js';import {EQUIPMENT,CLOTHES} from './economy.js';import {createTrack,stream} from './music.js';import {shopHTML} from './shop.js';import {inventoryHTML} from './inventory.js';import {apartmentHTML} from './apartment.js';import {streamHTML} from './streaming.js';import {DISCS} from './discs.js';import {DIALOGUES} from './dialogue.js';import {toast} from './ui.js';
const $=id=>document.getElementById(id);
const ASSETS={laptop:'https://opengameart.org/sites/default/files/misc_electronics_sheet.png'};
function load(src){const i=new Image();i.src=src;return i}const laptop=load(ASSETS.laptop);
export class Game{
 constructor(canvas,state){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.s=state;this.keys={};this.projectiles=[];this.noteParticles=[];this.particles=new Particles();this.camera=0;this.level=LEVELS.city;this.player=new Player(150,630);this.player.hp=state.health;this.player.maxHp=state.maxHealth;this.player.music=state.musicEnergy;this.paused=false;this.boss=null;this.dialog=null;this.running=false;this.last=performance.now();this.onKeyDown=e=>{this.keys[e.key.toLowerCase()]=true;if(['a','d','w','e','j','k','q','shift',' '].includes(e.key.toLowerCase()))e.preventDefault();if(e.key.toLowerCase()==='escape')this.pause()};this.onKeyUp=e=>this.keys[e.key.toLowerCase()]=false;this.onCanvasClick=e=>this.canvasClick(e);this.onResize=()=>this.resize();window.addEventListener('keydown',this.onKeyDown,{passive:false});window.addEventListener('keyup',this.onKeyUp);window.addEventListener('resize',this.onResize);canvas.addEventListener('click',this.onCanvasClick);this.resize()}
 destroy(){this.running=false;cancelAnimationFrame(this.frame);window.removeEventListener('keydown',this.onKeyDown);window.removeEventListener('keyup',this.onKeyUp);window.removeEventListener('resize',this.onResize);this.canvas.removeEventListener('click',this.onCanvasClick)}
 resize(){const d=devicePixelRatio||1;this.canvas.width=innerWidth*d;this.canvas.height=innerHeight*d;this.ctx.setTransform(d,0,0,d,0,0);this.W=innerWidth;this.H=innerHeight}
 start(){if(this.running)return;this.running=true;this.last=performance.now();this.frame=requestAnimationFrame(t=>this.loop(t));if(!this.s.story.prologue){this.s.story.prologue=true;this.startDialogue(DIALOGUES.prologue,()=>{this.toast('Выйди в город и найди друга');this.autosave()})}}
 loop(t){if(!this.running)return;const dt=Math.min(.033,(t-this.last)/1000);this.last=t;if(!this.paused)this.update(dt);this.draw();this.frame=requestAnimationFrame(x=>this.loop(x))}
 update(dt){this.player.update(dt,this.keys,this.level);this.camera=Math.max(0,Math.min(this.level.width-this.W,this.player.x-this.W*.4));this.projectiles.forEach(p=>p.update(dt));this.projectiles=this.projectiles.filter(p=>p.life>0&&p.x>-100&&p.x<this.level.width+100);if(this.boss){this.boss.update(dt,this);for(const p of this.projectiles){if(p.type==='music'&&p.x>this.boss.x&&p.x<this.boss.x+this.boss.w&&p.y>this.boss.y&&p.y<this.boss.y+this.boss.h){p.life=0;this.boss.takeDamage(p.damage,this)}}for(const p of this.projectiles){if(p.type==='danger'&&this.player.x+this.player.w>p.x-p.r&&this.player.x<p.x+p.r&&this.player.y+this.player.h>p.y-p.r&&this.player.y<p.y+p.r&&this.player.inv<=0){this.damage(1);p.life=0}}}this.noteParticles.forEach(n=>{n.x+=n.vx*dt;n.y+=n.vy*dt;n.vy-=8*dt;n.life-=dt;n.rot+=dt*3});this.noteParticles=this.noteParticles.filter(n=>n.life>0);this.particles.update(dt);this.player.music=Math.min(100,this.player.music+10*dt);this.updateHint();this.syncHUD()}
 draw(){const c=this.ctx;c.clearRect(0,0,this.W,this.H);drawBackground(c,this.level,this.W,this.H,this.camera);c.save();c.translate(-this.camera,0);for(const p of this.level.platforms){c.fillStyle=this.level.bg==='city'?'#252d47':this.level.bg==='home'?'#3a334f':this.level.bg==='basement'?'#343434':'#3b2535';c.fillRect(p.x,p.y,p.w,p.h);c.fillStyle='#111827';c.fillRect(p.x,p.y,p.w,5)}for(const o of this.level.objects)this.drawObject(c,o);this.noteParticles.forEach(n=>{c.save();c.globalAlpha=Math.max(0,n.life);c.translate(n.x,n.y);c.rotate(n.rot);c.fillStyle=n.color;c.font='24px monospace';c.fillText(n.glyph,0,0);c.restore()});this.projectiles.forEach(p=>p.draw(c));this.player.draw(c);if(this.boss)this.boss.draw(c);this.particles.draw(c);c.restore()}
 drawObject(c,o){const y=o.y;c.imageSmoothingEnabled=false;const x=o.x;
  if(o.type==='computer'&&laptop.complete&&laptop.naturalWidth){c.drawImage(laptop,64,0,32,32,x-28,y-42,56,56);return}
  if(o.type==='friend'){const img=this.player.sprite.stand;if(img.complete&&img.naturalWidth){c.save();c.filter='hue-rotate(90deg) saturate(1.35)';c.drawImage(img,x-24,y-66,48,48);c.restore()}return}
  if(o.type==='shop'){c.fillStyle='#241b38';c.fillRect(x-48,y-70,96,70);c.fillStyle='#5de1ff';c.fillRect(x-44,y-66,88,24);c.fillStyle='#0b1020';c.fillRect(x-35,y-36,70,30);c.fillStyle='#ff4d78';for(let i=0;i<5;i++)c.fillRect(x-44+i*18,y-66,9,24);c.fillStyle='#fff';c.font='10px monospace';c.fillText('SHOP',x-14,y-50);return}
  if(o.type==='bench'){c.fillStyle='#8b5a3c';c.fillRect(x-42,y-34,84,9);c.fillRect(x-38,y-22,76,8);c.fillStyle='#4d3427';c.fillRect(x-34,y-15,8,15);c.fillRect(x+26,y-15,8,15);return}
  if(o.type==='alley'){c.fillStyle='#5de1ff';c.beginPath();c.arc(x,y-25,20,0,Math.PI*2);c.fill();c.fillStyle='#10162b';c.beginPath();c.arc(x,y-25,14,0,Math.PI*2);c.fill();c.fillStyle='#a855f7';c.fillRect(x-9,y-29,18,8);return}
  if(o.type==='exit'){c.fillStyle='#16111f';c.fillRect(x-24,y-72,48,72);c.fillStyle='#5de1ff';c.fillRect(x-17,y-61,34,61);c.fillStyle='#16111f';c.fillRect(x+8,y-35,5,5);c.fillStyle='#ffffffaa';c.font='10px monospace';c.fillText(o.label,x-55,y-82);return}
  if(o.type==='studio'){c.fillStyle='#111827';c.fillRect(x-35,y-58,70,58);c.fillStyle='#a855f7';c.fillRect(x-28,y-51,56,40);c.fillStyle='#5de1ff';c.fillRect(x-8,y-43,16,24);c.fillStyle='#fff';c.fillRect(x-3,y-40,6,18);return}
 }
 syncHUD(){$('moneyHud').textContent='₽ '+this.s.money.toLocaleString('ru-RU');$('chapterHud').textContent='ГЛАВА '+this.s.currentChapter;$('musicFill').style.width=this.player.music+'%';$('hearts').innerHTML=Array.from({length:this.player.maxHp},(_,i)=>`<span class="heart ${i>=this.player.hp?'empty-heart':''}">${i<this.player.hp?'❤️':'🖤'}</span>`).join('');$('bossHud').classList.toggle('hidden',!this.boss);if(this.boss){$('bossFill').style.width=this.boss.hp/this.boss.maxHp*100+'%';$('bossName').textContent='BOSS — '+this.boss.name;$('bossPhase').textContent='PHASE '+this.boss.phase}}
 nearObject(){return this.level.objects.find(o=>Math.abs(o.x-this.player.x)<95&&Math.abs(o.y-(this.player.y+this.player.h))<95)}
 updateHint(){const o=this.nearObject();const text=o?(o.type==='exit'?`E — ${o.label}`:({computer:'E — создать бит (+25 ₽)',shop:'E — зайти в магазин',friend:'E — поговорить',alley:'E — обыскать переулок',bench:'E — передохнуть',studio:'E — записать трек'}[o.type]||'E — взаимодействовать')):'';$('interactionHint').textContent=text}
 canvasClick(e){const r=this.canvas.getBoundingClientRect(),x=e.clientX-r.left+this.camera,y=e.clientY-r.top;if(this.level.objects.some(o=>o.type==='computer'&&Math.abs(o.x-x)<80&&Math.abs(o.y-y)<100))this.clickComputer()}
 interact(){const o=this.nearObject();if(!o)return;if(o.type==='exit')return this.changeLevel(o.target);return({computer:()=>this.clickComputer(),shop:()=>this.openShop(),alley:()=>this.findDisc(),bench:()=>this.toast('Иногда пауза тоже часть трека.'),friend:()=>this.meetFriend(),studio:()=>this.publish()})[o.type]?.()}
 changeLevel(id){const next=LEVELS[id];if(!next)return this.toast('Локация пока недоступна');if(id==='basement'&&!this.s.unlockedLocations.includes('basement'))return this.toast('Сначала поговори с другом');this.level=next;this.boss=null;this.player.x=id==='city'?120:80;this.player.y=630;this.player.vx=0;this.player.vy=0;this.camera=0;this.paused=false;this.toast('ЛОКАЦИЯ: '+next.name);this.autosave()}
 startDialogue(lines,onEnd){this.dialog={lines,index:0,onEnd};this.paused=true;this.renderDialogue()}
 renderDialogue(){const [speaker,line]=this.dialog.lines[this.dialog.index];$('panelContent').innerHTML=`<div class="small-label">${speaker}</div><h1>${speaker}</h1><p>${line.replace('{name}',this.s.playerName)}</p><button data-dialog-next>${this.dialog.index===this.dialog.lines.length-1?'ПРОДОЛЖИТЬ':'ДАЛЕЕ'}</button>`;$('panelScreen').classList.remove('hidden')}
 nextDialogue(){if(!this.dialog)return;if(++this.dialog.index<this.dialog.lines.length)return this.renderDialogue();const done=this.dialog.onEnd;this.dialog=null;$('panelScreen').classList.add('hidden');this.paused=false;done?.()}
 meetFriend(){if(this.s.story.friendMet)return this.changeLevel('basement');this.startDialogue(DIALOGUES.friend,()=>{this.s.story.friendMet=true;this.s.story.basement=true;if(!this.s.unlockedLocations.includes('basement'))this.s.unlockedLocations.push('basement');this.changeLevel('basement');this.autosave()})}
 clickComputer(){this.s.money+=25;this.spawnNotes();toast('+25 ₽');this.particles.burst(this.player.x+20,this.player.y,'#ffd166',8,3);this.autosave()}
 spawnNotes(){const computer=this.level.objects.find(o=>o.type==='computer');const ox=computer?computer.x:this.player.x+this.player.facing*5,oy=computer?computer.y-48:this.player.y+18;for(let i=0;i<7;i++)this.noteParticles.push({x:ox+(Math.random()*16-8),y:oy,vx:(Math.random()-.5)*45,vy:-55-Math.random()*55,life:1.2+Math.random()*.5,rot:Math.random()*2,glyph:i%2?'♫':'♪',color:i%3?'#5de1ff':'#a855f7'})}
 attack(music=false){if(this.player.attackCd>0)return;if(music){if(this.player.music<20)return this.toast('Недостаточно MUSIC');this.player.music-=20;this.projectiles.push(new Projectile(this.player.x+(this.player.facing>0?45:-10),this.player.y+30,this.player.facing*12,0,55,'music',11));this.player.attackCd=.22;this.particles.burst(this.player.x+this.player.facing*35,this.player.y+30,'#5de1ff',7,4)}else{this.player.attackCd=.3;for(const p of this.projectiles)if(p.type==='danger'&&Math.abs(p.x-this.player.x)<90)p.life=0}}
 special(){if(this.player.music<45)return this.toast('Нужно 45 MUSIC');this.player.music-=45;this.projectiles.push(new Projectile(this.player.x,this.player.y,this.player.facing*15,-1,80,'music',24));this.toast('BEAT DROP!')}
 damage(n){if(this.player.inv>0)return;this.player.hp-=n;this.player.inv=.9;this.player.vx=-this.player.facing*6;this.particles.burst(this.player.x,this.player.y+30,'#ff496d',14,5);if(this.player.hp<=0)this.lose()}
 lose(){this.paused=true;this.s.health=3;this.s.musicEnergy=100;this.player.hp=3;this.player.music=100;$('panelContent').innerHTML='<h1>ВЫ ПРОИГРАЛИ</h1><p>Кажется, школа всё-таки ждёт вас...</p><button data-retry-boss>ПОПРОБОВАТЬ ЕЩЁ РАЗ</button>';$('panelScreen').classList.remove('hidden')}
 bossDefeated(b){if(!this.s.bossesDefeated.includes('mom'))this.s.bossesDefeated.push('mom');this.boss=null;this.paused=true;this.s.health=3;$('panelContent').innerHTML=`<h1>BOSS DEFEATED</h1><p>${b.name} повержен. Путь продолжается.</p><button data-close-panel>ПРОДОЛЖИТЬ</button>`;$('panelScreen').classList.remove('hidden');this.autosave()}
 startMom(){this.level=LEVELS.boss;this.player.x=200;this.player.y=630;this.boss=createBoss('mom');this.toast('BOSS — МАМА')}
 openShop(){this.paused=true;$('panelContent').innerHTML=shopHTML(this.s);$('panelScreen').classList.remove('hidden')};openInventory(){this.paused=true;$('panelContent').innerHTML=inventoryHTML(this.s);$('panelScreen').classList.remove('hidden')};openApartment(){this.paused=true;$('panelContent').innerHTML=apartmentHTML(this.s);$('panelScreen').classList.remove('hidden')};openStream(){this.paused=true;$('panelContent').innerHTML=streamHTML(this.s);$('panelScreen').classList.remove('hidden')}
 publish(){const r=createTrack(this.s,'My First Track');this.toast(`ТРЕК ГОТОВ • ${r.quality}/100 • +${r.income} ₽`);this.autosave();if(this.s.equipment.mic!=='old'&&!this.s.bossesDefeated.includes('mom'))this.startDialogue(DIALOGUES.momBoss,()=>this.startMom())}
 doStream(){const r=stream(this.s);if(!r)return this.toast('Нужны камера и компьютер');this.toast(`LIVE • ${r.viewers} зрителей • +${r.income} ₽`);this.autosave();$('panelScreen').classList.add('hidden');this.paused=false}
 buyEquip(type,id){const item=EQUIPMENT[type]?.[id];if(!item||this.s.money<item.price)return this.toast('Недостаточно денег');this.s.money-=item.price;this.s.equipment[type]=id;this.toast('КУПЛЕНО');this.autosave();this.openShop()};buyCloth(id){const c=CLOTHES.find(x=>x[0]===id);if(!c||this.s.clothes.includes(id)||this.s.money<c[2])return;this.s.money-=c[2];this.s.clothes.push(id);this.s.equippedClothes.push(id);this.autosave();this.openShop()};buyFurniture(id){const prices={bed:5000,sofa:8000,tv:12000,desk:3000,speakers:15000,panels:22000,rgb:10000,chair:7000},price=prices[id];if(!price||this.s.furniture.includes(id)||this.s.money<price)return;this.s.money-=price;this.s.furniture.push(id);this.autosave();this.openApartment()}
 findDisc(){const pool=DISCS.filter(d=>!this.s.discs.some(x=>x.id===d.id));if(!pool.length)return this.toast('Переулок уже пуст.');const d=pool[Math.floor(Math.random()*pool.length)];this.s.discs.push(d);this.toast('💿 НАЙДЕН ДИСК: '+d.name);this.autosave()};autosave(){this.s.health=this.player.hp;this.s.musicEnergy=this.player.music;Save.save(this.s)};toast(t){toast(t)};pause(){if(!$('panelScreen').classList.contains('hidden'))return;this.paused=!this.paused;$('pauseScreen').classList.toggle('hidden',!this.paused)}
}
