import {Save} from './save.js';
import {Game} from './game.js';
import {showScreen} from './ui.js';
import {LINKS} from './config.js';
import {CHARACTER_LIST} from './player.js';
let state=Save.load(),game=null,pendingStart=false,pendingCharacter=state.character||'robot';
const $=id=>document.getElementById(id);
function startGame(){if(game)game.destroy();game=new Game($('gameCanvas'),state);showScreen('gameScreen');setupMobileControls();game.start();window.game=game;refreshQuests()}
function showCharacters(forNew=false){pendingStart=forNew;pendingCharacter=state.character||'robot';renderCharacters();showScreen('characterScreen')}
function renderCharacters(){const grid=$('characterGrid');const names={robot:'REP-01',neon:'NEON',pixel:'PIXEL',classic:'CLASSIC'};grid.innerHTML=Object.entries(CHARACTER_LIST).map(([id,a])=>`<button class="character-card ${id===pendingCharacter?'selected':''}" data-character="${id}"><span class="character-preview ${id}"><img src="${a.idle}" alt="${names[id]}"></span><b>${names[id]}</b><small>${id==='robot'?'Пиксельный робот':id==='neon'?'Неоновый герой':id==='pixel'?'Уличный пиксель':'Классический герой'}</small></button>`).join('');$('characterSelected').textContent='Выбран: '+names[pendingCharacter]}
function setupMobileControls(){const box=$('mobileControls');if(!box||!game)return;const touch=matchMedia('(pointer:coarse)').matches||('ontouchstart' in window);box.classList.toggle('hidden',!touch);box.querySelectorAll('[data-key]').forEach(btn=>{const key=btn.dataset.key;const down=e=>{e.preventDefault();if(!game||game.paused)return;if(key==='j')return game.attack(false);if(key==='k')return game.attack(true);if(key==='e')return game.interact();if(key==='q')return game.special();game.keys[key]=true;btn.classList.add('pressed')};const up=e=>{e.preventDefault();if(game)game.keys[key]=false;btn.classList.remove('pressed')};btn.addEventListener('pointerdown',down);btn.addEventListener('pointerup',up);btn.addEventListener('pointercancel',up);btn.addEventListener('pointerleave',up);});}
function openPanel(html){if(game)game.paused=true;$('panelContent').innerHTML=html;$('panelScreen').classList.remove('hidden')}
function refreshQuests(){const q=$('questHud');if(!q)return;const quests=[['tracks',state.tracks.length>=1,'Записать первый трек'],['friend',state.story.friendMet,'Найти друга и попасть в REP ПВЗ'],['money',state.money>=2500,'Заработать 2 500 ₽']];q.innerHTML=`<div class="quest"><b>QUEST LOG</b>${quests.map(x=>`<div class="${x[1]?'done':''}">${x[1]?'✓':'□'} ${x[2]}</div>`).join('')}<div class="quest-power">⚡ POWER: +${state.tracks.length*4} к MUSIC-атаке</div></div>`}
window.refreshQuests=refreshQuests;
$('metButton').onclick=()=>{if(LINKS.MET200&&LINKS.MET200!=='PASTE_LINK_HERE')location.href=LINKS.MET200;else alert('Укажи ссылку MET200$ в js/config.js')};
$('menuButtons').onclick=e=>{const a=e.target.dataset.action;if(a==='new'){state=Save.fresh();pendingCharacter='robot';$('nameInput').value='';showScreen('nameScreen')}if(a==='continue'){state=Save.load();if(!state.playerName)showScreen('nameScreen');else startGame()}if(a==='character')showCharacters(false);if(a==='collection')openPanel(`<h1>DISK COLLECTION</h1><div class="disc-grid">${Array.from({length:50},(_,i)=>{const d=state.discs.find(x=>x.id===i);return `<div class="card ${d?'':'locked'}"><div class="rarity">${d?.rarity||'UNKNOWN'}</div><h3>💿 ${d?.name||'???'}</h3><div class="stat">${d?'₽ '+d.value:'Не найден'}</div></div>`}).join('')}</div><button data-close-panel>ЗАКРЫТЬ</button>`);if(a==='settings')openPanel(`<h1>НАСТРОЙКИ</h1><p>Управление: A/D — движение, W — прыжок, E — взаимодействие.</p><button data-reset>СБРОСИТЬ СОХРАНЕНИЕ</button><button data-close-panel>ЗАКРЫТЬ</button>`)};
$('nameContinue').onclick=()=>{const n=$('nameInput').value.trim();if(!n)return;state.playerName=n;showCharacters(true)};
$('characterGrid').onclick=e=>{const card=e.target.closest('[data-character]');if(!card)return;pendingCharacter=card.dataset.character;renderCharacters()};
$('characterConfirm').onclick=()=>{state.character=pendingCharacter;Save.save(state);if(pendingStart){pendingStart=false;startGame();game.toast('Добро пожаловать, '+state.playerName+'!')}else showScreen('menu')};
document.addEventListener('click',e=>{const t=e.target;if(t.dataset.pause){const a=t.dataset.pause;if(a==='resume'){$('pauseScreen').classList.add('hidden');game.paused=false}if(a==='inventory'){game.openInventory();$('pauseScreen').classList.add('hidden')}if(a==='apartment'){game.openApartment();$('pauseScreen').classList.add('hidden')}if(a==='map'){openPanel('<h1>КАРТА</h1><p>🏠 Дом　🏙 Город　📦 REP ПВЗ　🏪 Магазин　🎵 Студия　🎤 Арена</p><button data-close-panel>ЗАКРЫТЬ</button>');$('pauseScreen').classList.add('hidden')}if(a==='settings'){openPanel('<h1>НАСТРОЙКИ</h1><p>A/D/W/E на ПК и кнопки на телефоне.</p><button data-reset>СБРОСИТЬ СОХРАНЕНИЕ</button><button data-close-panel>ЗАКРЫТЬ</button>');$('pauseScreen').classList.add('hidden')}if(a==='save'){game.autosave();game.toast('СОХРАНЕНО')}if(a==='menu'){game.autosave();showScreen('menu');$('pauseScreen').classList.add('hidden')}}if(t.dataset.closePanel!==undefined){$('panelScreen').classList.add('hidden');if(game)game.paused=false}if(t.dataset.retryBoss){$('panelScreen').classList.add('hidden');game.paused=false;game.startMom()}if(t.dataset.dialogNext!==undefined)game.nextDialogue();if(t.dataset.buyEquip){const [type,id]=t.dataset.buyEquip.split(':');game.buyEquip(type,id)}if(t.dataset.buyCloth)game.buyCloth(t.dataset.buyCloth);if(t.dataset.buyFurniture)game.buyFurniture(t.dataset.buyFurniture);if(t.dataset.stream)game.doStream();if(t.dataset.reset){Save.clear();location.reload()}});
window.addEventListener('keydown',e=>{if(!game)return;const k=e.key.toLowerCase();if(k==='e'&&!e.repeat&&!game.paused){e.preventDefault();game.interact();return}if(game.paused)return;if(k==='j')game.attack(false);if(k==='k')game.attack(true);if(k==='q')game.special()},{passive:false});
refreshQuests();
