import {Player} from "./player.js";import {Particles} from "./particles.js";import {Projectile} from "./combat.js";import {LEVELS,drawBackground} from "./levels.js";import {createBoss} from "./bosses.js";import {Save} from "./save.js";import {equipmentStats,EQUIPMENT,CLOTHES} from "./economy.js";import {createTrack,stream} from "./music.js";import {shopHTML} from "./shop.js";import {inventoryHTML} from "./inventory.js";import {apartmentHTML} from "./apartment.js";import {streamHTML} from "./streaming.js";import {DISCS} from "./discs.js";import {QUESTS} from "./quests.js";import {toast} from "./ui.js";

export class Game{
constructor(canvas,state){this.canvas=canvas;this.ctx=canvas.getContext("2d");this.s=state;this.keys={};this.projectiles=[];this.particles=new Particles();this.camera=0;this.level=LEVELS.city;this.player=new Player(150,600);this.player.hp=state.health;this.player.maxHp=state.maxHealth;this.player.music=state.musicEnergy;this.paused=false;this.boss=null;this.dialog=null;this.last=performance.now();this.setup();this.resize();window.addEventListener("resize",()=>this.resize())}
setup(){window.onkeydown=e=>{const k=e.key.toLowerCase();this.keys[k]=true;if(k==="escape")this.pause()};window.onkeyup=e=>this.keys[e.key.toLowerCase()]=false}
resize(){this.canvas.width=innerWidth*devicePixelRatio;this.canvas.height=innerHeight*devicePixelRatio;this.ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);this.W=innerWidth;this.H=innerHeight}
start(){requestAnimationFrame(t=>this.loop(t))}
loop(t){const dt=Math.min(.033,(t-this.last)/1000);this.last=t;if(!this.paused)this.update(dt);this.draw();requestAnimationFrame(x=>this.loop(x))}
update(dt){if(this.dialog)return;this.player.update(dt,this.keys,this.level);this.camera=Math.max(0,Math.min(this.level.width-this.W,this.player.x-this.W*.4));this.projectiles.forEach(p=>p.update(dt));this.projectiles=this.projectiles.filter(p=>p.life>0&&p.x>-100&&p.x<this.level.width+100);if(this.boss){this.boss.update(dt,this);for(const p of this.projectiles){if(p.type==="music"&&p.x>this.boss.x&&p.x<this.boss.x+this.boss.w&&p.y>this.boss.y&&p.y<this.boss.y+this.boss.h){p.life=0;this.boss.takeDamage(p.damage,this)}}for(const p of this.projectiles){if(p.type==="danger"&&this.player.x+this.player.w>p.x-p.r&&this.player.x<p.x+p.r&&this.player.y+this.player.h>p.y-p.r&&this.player.y<p.y+p.r&&this.player.inv<=0){this.damage(1);p.life=0}}}this.particles.update(dt);this.player.music=Math.min(100,this.player.music+10*dt);this.syncHUD()}
draw(){const c=this.ctx;c.clearRect(0,0,this.W,this.H);drawBackground(c,this.level,this.W,this.H,this.camera);c.save();c.translate(-this.camera,0);for(const p of this.level.platforms){c.fillStyle=this.level.bg==="city"?"#252d47":"#343434";c.fillRect(p.x,p.y,p.w,p.h);c.fillStyle="#111827";c.fillRect(p.x,p.y,p.w,5)}for(const o of this.level.objects){c.font="28px sans-serif";c.fillText(o.type==="computer"?"💻":o.type==="shop"?"🏪":o.type==="bench"?"🪑":"🚪",o.x,o.y)}this.projectiles.forEach(p=>p.draw(c));this.player.draw(c);if(this.boss)this.boss.draw(c);this.particles.draw(c);c.restore()}
syncHUD(){document.getElementById("moneyHud").textContent="₽ "+this.s.money.toLocaleString("ru-RU");document.getElementById("musicFill").style.width=this.player.music+"%";let h="";for(let i=0;i<this.player.maxHp;i++)h+=`<span class="heart ${i>=this.player.hp?"empty-heart":""}">${i<this.player.hp?"❤️":"🖤"}</span>`;document.getElementById("hearts").innerHTML=h;if(this.boss){document.getElementById("bossHud").classList.remove("hidden");document.getElementById("bossFill").style.width=(this.boss.hp/this.boss.maxHp*100)+"%";document.getElementById("bossName").textContent="BOSS — "+this.boss.name;document.getElementById("bossPhase").textContent="PHASE "+this.boss.phase}else document.getElementById("bossHud").classList.add("hidden")}
clickComputer(){this.s.money+=25;toast("+25 ₽");this.particles.burst(this.player.x+20,this.player.y,"#ffd166",8,3);this.autosave()}
attack(music=false){if(this.player.attackCd>0)return;if(music){if(this.player.music<20)return;this.player.music-=20;this.projectiles.push(new Projectile(this.player.x+(this.player.facing>0?45:-10),this.player.y+30,this.player.facing*12,0,55,"music",11));this.player.attackCd=.22;this.particles.burst(this.player.x+this.player.facing*35,this.player.y+30,"#5de1ff",7,4)}else{this.player.attackCd=.3;for(const p of this.projectiles)if(p.type==="danger"&&Math.abs(p.x-this.player.x)<90){p.life=0}}}
damage(n){if(this.player.inv>0)return;this.player.hp-=n;this.player.inv=.9;this.player.vx=-this.player.facing*6;this.particles.burst(this.player.x,this.player.y+30,"#ff496d",14,5);if(this.player.hp<=0)this.lose()}
warning(r){this.particles.burst(r.x+r.w/2,r.y,"#ff496d",20,2)}
lose(){this.paused=true;this.s.health=3;this.s.musicEnergy=100;this.player.hp=3;this.player.music=100;document.getElementById("panelContent").innerHTML=`<h1>ВЫ ПРОИГРАЛИ</h1><p>Кажется, школа всё-таки ждёт вас...</p><button data-retry-boss>ПОПРОБОВАТЬ ЕЩЁ РАЗ</button>`;document.getElementById("panelScreen").classList.remove("hidden")}
bossDefeated(b){this.s.bossesDefeated.push(b.name==="МАМА"?"mom":b.name);this.boss=null;this.paused=true;this.s.health=3;document.getElementById("panelContent").innerHTML=`<h1>BOSS DEFEATED</h1><p>${b.name} повержен. Путь продолжается.</p><button data-close-panel>ПРОДОЛЖИТЬ</button>`;document.getElementById("panelScreen").classList.remove("hidden");this.autosave()}
startMom(){this.level=LEVELS.boss;this.player.x=200;this.player.y=600;this.boss=createBoss("mom");this.toast("BOSS — МАМА")}
openShop(){this.paused=true;document.getElementById("panelContent").innerHTML=shopHTML(this.s);document.getElementById("panelScreen").classList.remove("hidden")}
openInventory(){this.paused=true;document.getElementById("panelContent").innerHTML=inventoryHTML(this.s);document.getElementById("panelScreen").classList.remove("hidden")}
openApartment(){this.paused=true;document.getElementById("panelContent").innerHTML=apartmentHTML(this.s);document.getElementById("panelScreen").classList.remove("hidden")}
openStream(){this.paused=true;document.getElementById("panelContent").innerHTML=streamHTML(this.s);document.getElementById("panelScreen").classList.remove("hidden")}
publish(){const r=createTrack(this.s,"My First Track");this.toast(`ТРЕК ГОТОВ • ${r.quality}/100 • +${r.income} ₽`);this.autosave()}
doStream(){const r=stream(this.s);if(r){this.toast(`LIVE • ${r.viewers} зрителей • +${r.income} ₽`);this.autosave();document.getElementById("panelScreen").classList.add("hidden");this.paused=false}}
buyEquip(type,id){const price=EQUIPMENT[type][id].price;if(this.s.money<price)return;this.s.money-=price;this.s.equipment[type]=id;this.toast("КУПЛЕНО");this.autosave();this.openShop()}
buyCloth(id){const c=CLOTHES.find(x=>x[0]===id);if(this.s.money<c[2])return;this.s.money-=c[2];this.s.clothes.push(id);this.s.equippedClothes.push(id);this.autosave();this.openShop()}
buyFurniture(id){const list=[["bed",5000],["sofa",8000],["tv",12000],["desk",3000],["speakers",15000],["panels",22000],["rgb",10000],["chair",7000]];const f=list.find(x=>x[0]===id);if(!f||this.s.money<f[1])return;this.s.money-=f[1];this.s.furniture.push(id);this.autosave();this.openApartment()}
findDisc(){const pool=DISCS.filter(d=>!this.s.discs.some(x=>x.id===d.id));if(!pool.length)return;const d=pool[Math.floor(Math.random()*pool.length)];this.s.discs.push(d);this.toast("💿 НАЙДЕН ДИСК: "+d.name);this.autosave()}
autosave(){this.s.health=this.player.hp;this.s.musicEnergy=this.player.music;Save.save(this.s)}
toast(t){toast(t)}
pause(){if(document.getElementById("panelScreen").classList.contains("hidden")===false)return;this.paused=!this.paused;document.getElementById("pauseScreen").classList.toggle("hidden",!this.paused)}}
